'use strict';
const $=id=>document.getElementById(id),el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f;}catch{return f;}};
let trips=read('sm_trips',[]),history=read('sm_hist',[]),ids=read('sm_loginIds',{}),notified=read('sm_notified',{}),activeId=localStorage.getItem('sm_active'),editing=null,draft=[],imageURL=null,selectedImage=null,ocrBusy=false,formVersion=0,toastTimer,staged=null,importMeta=null;
if(!Array.isArray(trips))trips=[];if(!Array.isArray(history))history=[];
const uid=()=>crypto.randomUUID?crypto.randomUUID():'t'+Date.now()+Math.random().toString(36).slice(2);
const active=()=>trips.find(t=>t.id===activeId)||trips[0]||null;
const button=(label,fn,cls='secondary')=>{const b=el('button',label,cls);b.type='button';b.addEventListener('click',fn);return b;};
function toast(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,5500);}
function persist(){try{localStorage.setItem('sm_trips',JSON.stringify(trips));localStorage.setItem('sm_hist',JSON.stringify(history));if(active())localStorage.setItem('sm_active',active().id);else localStorage.removeItem('sm_active');return true;}catch{toast('端末への保存に失敗しました。空き容量を確認してください。');return false;}}
function show(page){if(['ride','check','history'].includes(page)&&!active()){toast('先に乗車を登録してください');page='home';}document.querySelectorAll('.screen').forEach(e=>e.classList.toggle('active',e.id===page));document.querySelectorAll('nav button').forEach(e=>e.classList.toggle('selected',e.dataset.page===page));render();scrollTo(0,0);}
async function copy(text){if(!text)return toast('コピーする情報がありません');try{await navigator.clipboard.writeText(text);toast('コピーしました');}catch{prompt('文字を選択してコピーしてください',text);}}
function resetForm(t){formVersion++;staged=null;importMeta=t?.importMeta||null;$('importReview').hidden=true;$('registerTitle').textContent=t?'乗車を編集':'乗車を登録';editing=t?.id||null;for(const k of ['date','train','from','to','car','seat','neighbor','notifyBefore'])$(k).value=t?.[k]??(k==='date'?new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo'}).format(new Date()):k==='notifyBefore'?'10':'');draft=(t?.stops||[]).map(s=>({...s}));$('shot').value='';selectedImage=null;$('ocrText').value='';$('preview').hidden=true;$('ocrRun').disabled=true;$('formError').textContent='';$('ocrStatus').textContent='画像は端末内で処理し、保存しません。初回はOCRの読み込みに通信が必要です。';if(imageURL)URL.revokeObjectURL(imageURL);imageURL=null;renderEditor();show('register');}
function newTrip(){if(ocrBusy)return toast('OCRの完了をお待ちください');if(trips.length>=5)return toast('保存は最大5件です。不要な乗車を削除してください。');resetForm(null);}
function edit(){if(ocrBusy)return toast('OCRの完了をお待ちください');if(active())resetForm(active());}
function renderEditor(){const root=$('stopEditor');root.replaceChildren();draft.forEach((s,i)=>{const card=el('div',undefined,'stopedit'),row=el('div',undefined,'row');row.append(el('b',`${i+1}`),button('↑',()=>{if(i){[draft[i-1],draft[i]]=[draft[i],draft[i-1]];renderEditor();}}),button('↓',()=>{if(i<draft.length-1){[draft[i+1],draft[i]]=[draft[i],draft[i+1]];renderEditor();}}),button('削除',()=>{draft.splice(i,1);renderEditor();},'danger'));card.append(row);const field=(key,label,type)=>{const wrap=el('div'),l=el('label',label),input=el('input');input.id=`stop-${i}-${key}`;l.htmlFor=input.id;input.type=type;input.value=s[key]||'';input.addEventListener('input',()=>s[key]=input.value);wrap.append(l,input);return wrap;};card.append(field('name','駅名','text'));const g=el('div',undefined,'grid');g.append(field('arr','到着','time'),field('dep','出発','time'));card.append(g);root.append(card);});}
function formFields(){return Object.fromEntries(['date','train','from','to','car','seat'].map(k=>[k,$(k).value.trim()]));}
function parse(text){
 if(!String(text).trim())return toast('テキストを貼り付けるか、画像を読み取ってください');
 if(String(text).length>100000)return toast('取り込む列車1本分にテキストを絞ってください');
 staged=SM.parseTransit(text,Number($('date').value.slice(0,4))||undefined);
 $('importMode').value=!editing&&draft.length?'merge':'replace';$('applyFields').checked=!editing;
 $('importReview').hidden=false;renderReview();$('importReview').scrollIntoView({block:'start'});toast('抽出しました。候補と変更内容を確認してください');
}
function renderReview(){
 if(!staged)return;const existing=formFields(),fields=staged.fields;const warnings=[...staged.warnings];
 const same=(a,b)=>String(a||'').normalize('NFKC').replace(/\s/g,'');
 const mismatched=!!editing&&((fields.train&&existing.train&&!same(fields.train,existing.train))||(fields.date&&fields.date!==existing.date));
 if(editing&&(!fields.train||!fields.date))warnings.push('列車名または乗車日を読み取れていません。選択中の乗車に合う情報か確認してください。');
 if(mismatched)warnings.push('選択中の乗車と列車名または日付が異なります。この乗車には反映できません。正しい情報を取り込むか、新しい乗車を登録してください。');
 $('reviewTitle').textContent=editing?'現在の時刻表との比較':'抽出した乗車情報';$('identityHint').textContent=editing?'更新時は日付・列車名・乗降駅を通常は保持します。号車・座席・隣席・確認履歴も引き継ぎます。':'切符画像に号車・座席があれば、新規登録に反映します。';
 $('importWarnings').replaceChildren();warnings.forEach(w=>$('importWarnings').append(el('p',w,'notice')));
 $('importFields').replaceChildren();const labels={date:'乗車日',train:'列車名',from:'乗車駅候補',to:'降車駅候補',car:'号車',seat:'座席'};
 Object.entries(fields).forEach(([k,v])=>{if(labels[k])$('importFields').append(el('p',`${labels[k]}：${v}`));});
 const plan=SM.planStops(draft,staged.stops,$('importMode').value);const summary=el('p',`更新後 ${plan.stops.length}駅 / 変更 ${plan.changes.length}件`);$('importDiff').replaceChildren(summary);
 const time=s=>s?`${s.arr?'着 '+s.arr:'着 —'} / ${s.dep?'発 '+s.dep:'発 —'}`:'—';
 const table=el('table',undefined,'diff-table'),head=el('tr');['駅 / 変更','現在','取り込み後'].forEach(x=>head.append(el('th',x)));const thead=el('thead');thead.append(head);table.append(thead);const body=el('tbody');
 plan.stops.forEach(next=>{const old=draft.find(s=>s.name===next.name),change=plan.changes.find(c=>c.name===next.name),row=el('tr',undefined,change?'changed':'');row.append(el('th',next.name+(change?' / '+change.type:'')),el('td',time(old)),el('td',time(next)));body.append(row);});
 plan.changes.filter(c=>c.type==='削除').forEach(c=>{const row=el('tr',undefined,'removed');row.append(el('th',c.name+' / 削除'),el('td',time(c.before)),el('td','—'));body.append(row);});table.append(body);$('importDiff').append(table);
 $('applyImport').disabled=staged.blocked||mismatched||(!staged.stops.length&&!Object.keys(fields).length);
}
$('importMode').addEventListener('change',renderReview);$('applyFields').addEventListener('change',renderReview);
$('applyImport').addEventListener('click',()=>{
 if(!staged||$('applyImport').disabled)return;
 const plan=SM.planStops(draft,staged.stops,$('importMode').value);
 const fields=$('applyFields').checked?staged.fields:{};
 const from=fields.from||$('from').value,to=fields.to||$('to').value;
 if(staged.stops.length&&$('importMode').value==='replace'&&draft.length&&((from&&!plan.stops.some(s=>s.name===from))||(to&&!plan.stops.some(s=>s.name===to))))return toast('乗車駅か降車駅が候補にありません。分割画像なら「追加・時刻更新」を選択してください');
 if($('applyFields').checked){for(const[k,v]of Object.entries(fields)){if(['date','train','from','to'].includes(k)||!editing&&['car','seat'].includes(k))$(k).value=v;}}
 if(staged.stops.length)draft=plan.stops;
 importMeta={source:'user-import',importedAt:new Date().toISOString(),mode:$('importMode').value};
 $('parseQuality').textContent=`取り込みを反映：${draft.length}駅。停車順・乗車日・着発時刻を確認して保存してください。`;
 staged=null;$('importReview').hidden=true;renderEditor();toast('編集内容に反映しました。確認後に保存してください');
});
$('discardImport').addEventListener('click',()=>{staged=null;$('importReview').hidden=true;toast('候補を破棄しました');});
$('pasteText').addEventListener('click',async()=>{try{const text=await navigator.clipboard.readText();if(!text.trim())return toast('クリップボードにテキストがありません');$('ocrText').value=text;parse(text);}catch{toast('テキスト欄を長押しして「ペースト」してください');$('ocrText').focus();}});
$('ocrText').addEventListener('input',()=>{if(staged){staged=null;$('importReview').hidden=true;}});
let loader;
function loadOCR(){if(window.Tesseract)return Promise.resolve();if(loader)return loader;loader=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@6.0.1/dist/tesseract.min.js';const timeout=setTimeout(()=>{s.remove();loader=null;reject(new Error('timeout'));},45000);s.onload=()=>{clearTimeout(timeout);resolve();};s.onerror=()=>{clearTimeout(timeout);s.remove();loader=null;reject(new Error('load'));};document.head.append(s);});return loader;}
function chooseImage(f){selectedImage=f||null;if(imageURL)URL.revokeObjectURL(imageURL);$('preview').hidden=true;$('ocrRun').disabled=!f;if(!f)return;if(!f.type.startsWith('image/')){$('ocrRun').disabled=true;return toast('画像ファイルを選択してください');}imageURL=URL.createObjectURL(f);$('preview').src=imageURL;$('preview').hidden=false;}
$('shot').addEventListener('change',()=>chooseImage($('shot').files[0]));
$('ocrText').addEventListener('paste',e=>{const file=[...(e.clipboardData?.items||[])].find(item=>item.type.startsWith('image/'))?.getAsFile();if(file){e.preventDefault();chooseImage(file);toast('画像を貼り付けました。「画像をOCRで読み取る」を押してください');}});
$('ocrRun').addEventListener('click',async()=>{const file=selectedImage;if(!file||ocrBusy)return;ocrBusy=true;const version=formVersion;$('ocrRun').disabled=true;$('shot').disabled=true;$('parse').disabled=true;$('pasteText').disabled=true;let worker;
 try{$('ocrStatus').textContent='OCRを準備しています…';await loadOCR();worker=await Tesseract.createWorker(['jpn','eng'],1,{logger:m=>{if(m.status==='recognizing text')$('ocrStatus').textContent=`読み取り中 ${Math.round(m.progress*100)}%`;}});const result=await worker.recognize(file);if(version===formVersion){$('ocrText').value=result.data.text;parse(result.data.text);$('ocrStatus').textContent='読み取り完了。候補を確認・修正してください。';}}
 catch{$('ocrStatus').textContent='OCRを実行できませんでした。通信・画像形式を確認して再試行するか、テキスト貼り付け・手入力をご利用ください。';}
 finally{if(worker)await worker.terminate().catch(()=>{});ocrBusy=false;$('ocrRun').disabled=false;$('shot').disabled=false;$('parse').disabled=false;$('pasteText').disabled=false;}});
$('parse').addEventListener('click',()=>parse($('ocrText').value));$('addStop').addEventListener('click',()=>{draft.push({name:'',arr:null,dep:null});renderEditor();});
$('tripForm').addEventListener('submit',e=>{e.preventDefault();if(ocrBusy)return toast('OCRの完了後に保存してください');if(staged)return toast('取り込み候補を反映するか破棄してから保存してください');const o={id:editing||uid(),...Object.fromEntries(['date','train','from','to','car','seat','neighbor'].map(k=>[k,$(k).value.trim()])),importMeta,notifyBefore:Number($('notifyBefore').value),stops:draft.map(s=>({name:s.name.trim(),arr:s.arr||null,dep:s.dep||null}))};const error=s=>{$('formError').textContent=s;};
 if(!editing&&trips.length>=5)return error('保存は5件までです。');if(o.from===o.to)return error('乗車駅と降車駅を別々に指定してください。');if(!/^\d{1,2}$/.test(o.car))return error('号車は数字で指定してください。');o.seat=o.seat.normalize('NFKC').toUpperCase();o.neighbor=o.neighbor.normalize('NFKC').toUpperCase();if(o.neighbor&&o.neighbor===o.seat)return error('あなたの座席と隣席を別々に指定してください。');
 if(o.stops.some(s=>!s.name))return error('空欄の駅を入力するか削除してください。');if(new Set(o.stops.map(s=>s.name)).size!==o.stops.length)return error('停車駅の重複を修正してください。');if(o.stops.some(s=>s.arr&&SM.mins(s.arr)===null||s.dep&&SM.mins(s.dep)===null))return error('時刻をHH:MMで入力してください。');
 if(o.stops.length){const a=o.stops.findIndex(s=>s.name===o.from),b=o.stops.findIndex(s=>s.name===o.to);if(a<0||b<=a)return error('乗車駅・降車駅を停車駅に含め、運行順に並べてください。');const tl=SM.timeline(o);if(tl.length&&tl.at(-1).at-tl[0].at>24*60*60000)return error('停車時刻が24時間を超えています。順番と時刻を確認してください。');}
 const old=trips.find(t=>t.id===editing);if(old){o.predictedStation=o.stops.some(s=>s.name===old.predictedStation)&&old.seat===o.seat&&old.neighbor===o.neighbor&&old.date===o.date&&old.car===o.car&&old.train===o.train?old.predictedStation:'';Object.assign(old,o);}else trips.push(o);activeId=o.id;if(persist()){show('home');toast('乗車を保存しました');}});
function option(select,value,text){const e=el('option',text);e.value=value;select.append(e);}
for(const s of SM.services){option($('serviceSelect'),s.id,s.name);option($('loginService'),s.id,s.name);}option($('serviceSelect'),'','選択してください');
let checkTrip=null;
function renderCheck(t,force=false){if(!t)return;const previousFrom=$('searchFrom').value,previousTo=$('searchTo').value,previousService=$('serviceSelect').value;const changed=checkTrip!==t.id||force;checkTrip=t.id;const service=SM.service(t.train);$('serviceSelect').value=changed?service?.id||'':previousService;$('serviceHint').textContent=service?`${service.name}を候補にしました。利用区間に応じて変更できます。`:'自動判定できません。予約サービスを選択してください。';
 const names=[...new Set([t.from,...(t.stops||[]).map(s=>s.name),t.to].filter(Boolean))];for(const id of ['searchFrom','searchTo']){$(id).replaceChildren();names.forEach(n=>option($(id),n,n));}const ts=SM.state(t);$('searchFrom').value=!changed&&names.includes(previousFrom)?previousFrom:ts.next?.name||t.from;$('searchTo').value=!changed&&names.includes(previousTo)?previousTo:t.to;renderCopies(t);}
function renderCopies(t){$('copyRows').replaceChildren();const service=$('serviceSelect').value;const rows=[['日付',t.date],['列車',t.train],['乗車駅',t.from],['降車駅',t.to],['号車',t.car],['確認する隣席',t.neighbor]];if(ids[service])rows.push(['ログインID',ids[service]]);rows.forEach(([k,v])=>{const row=el('div',undefined,'copyrow'),info=el('div');info.append(el('small',k),el('b',v||'未設定'));row.append(info,button('コピー',()=>copy(v)));$('copyRows').append(row);});}
function render(){const t=active();$('add').disabled=trips.length>=5;$('empty').hidden=!!trips.length;$('dashboard').hidden=!t;$('tripList').replaceChildren();trips.forEach(x=>{const row=el('div',undefined,`trip ${x.id===t?.id?'active':''}`),info=el('div');info.append(el('b',x.train),el('small',`${x.date} / ${x.from} → ${x.to}`));row.append(info,button(x.id===t?.id?'選択中':'切替',()=>{activeId=x.id;persist();render();}),button('削除',()=>{if(confirm('この乗車と座席確認履歴を削除しますか？')){trips=trips.filter(y=>y.id!==x.id);history=history.filter(h=>h.tripId!==x.id);if(activeId===x.id)activeId=trips[0]?.id;persist();render();}},'danger'));$('tripList').append(row);});if(!t)return;
 $('importStamp').textContent=t.importMeta?.importedAt?'情報の取り込み：'+new Date(t.importMeta.importedAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'}):'Yahoo!の最新情報を取り込んで時刻表を更新できます。';$('tripDate').textContent=t.date;$('trainTitle').textContent=t.train;$('route').textContent=`${t.from} → ${t.to}`;$('yourSeat').textContent=`${t.car}号車 ${t.seat}`;$('targetSeat').textContent=t.neighbor||'未設定';updateClock();renderInference(t);$('rideTitle').textContent=t.train;$('stops').replaceChildren();const ts=SM.state(t);(t.stops||[]).forEach(s=>{const d=el('div',undefined,`stop ${ts.next?.name===s.name?'next':''}`);d.append(el('b',s.name),el('div',`${s.arr?'着 '+s.arr+'　':''}${s.dep?'発 '+s.dep:''}`));$('stops').append(d);});if(!t.stops?.length)$('stops').textContent='時刻表が未登録です。編集から追加できます。';renderCheck(t);renderHistory(t);}
function renderInference(t){const inf=SM.infer(t,history);$('inference').textContent=inf?`${inf.from}からの検索では空席、${inf.to}からは使用不可。候補：${inf.candidates.join('・')}。${inf.legacy?'旧履歴には検索区間がないため参考情報です。':''}`:'同じ隣席・到着駅で、出発駅を変えて確認した空席→使用不可の記録がたまると候補を表示します。';$('adoption').hidden=!inf;$('unaccept').hidden=!t.predictedStation;const selected=$('candidate').value;$('candidate').replaceChildren();if(inf){inf.candidates.forEach(n=>option($('candidate'),n,n));if(inf.candidates.includes(selected))$('candidate').value=selected;}}
function duration(m){return m>=1440?`${Math.floor(m/1440)}日${Math.floor(m%1440/60)}時間`:m+'分';}
function updateClock(){const t=active();if(!t)return;const state=SM.state(t),p=SM.prediction(t);$('current').textContent=state.current;$('next').textContent=state.next?.name||'—';$('remaining').textContent=state.minutes!==null?`あと約 ${duration(state.minutes)}`:'';$('prediction').className=`notice ${p?.soon?'soon':''}`;$('prediction').textContent=t.predictedStation?p?(p.minutes<0?`${t.predictedStation}の登録時刻を過ぎました。`:`採用した駅：${t.predictedStation} / あと約${duration(p.minutes)}`):`${t.predictedStation}の時刻を登録してください。`:'推定駅はまだ採用されていません。';if(p?.soon){const key=[t.id,t.date,t.predictedStation,p.at,t.notifyBefore].join('|');if(!notified[key]&&!document.hidden){notified[key]=true;try{localStorage.setItem('sm_notified',JSON.stringify(notified));}catch{}const message=`${t.predictedStation}まであと約${p.minutes}分。隣席 ${t.neighbor} の乗車候補駅です。`;toast(message);if('Notification'in window&&Notification.permission==='granted'&&navigator.serviceWorker)navigator.serviceWorker.ready.then(r=>r.showNotification('SeatMate 接近案内',{body:message,tag:key,icon:'icon-192.png'})).catch(()=>{});}}}
function record(status){const t=active();if(!t)return;if(!t.neighbor)return toast('乗車情報の編集で、確認する隣席を指定してください');const a=$('searchFrom').value,b=$('searchTo').value,names=(t.stops||[]).map(s=>s.name);if(a===b)return toast('検索した出発駅と到着駅を別々に選んでください');if(names.includes(a)&&names.includes(b)&&names.indexOf(a)>=names.indexOf(b))return toast('検索区間を運行順に選んでください');history.unshift({id:uid(),tripId:t.id,train:t.train,date:t.date,car:t.car,seat:t.neighbor,status,searchFrom:a,searchTo:b,station:a,ts:new Date().toISOString()});if(persist()){renderInference(t);renderHistory(t);toast(`${a} → ${b}：${status}を記録しました`);}}
function renderHistory(t){$('historyList').replaceChildren();const records=history.filter(h=>h.tripId===t.id||!h.tripId&&h.train===t.train);if(!records.length)$('historyList').textContent='まだ確認履歴がありません。';records.forEach(h=>{const row=el('div',undefined,'historyitem');row.append(el('b',`${h.searchFrom||h.station||'地点未登録'} → ${h.searchTo||'到着駅未登録'}`),el('div',`${h.car||'—'}号車 ${h.seat} / ${h.status}`),el('small',h.ts?new Date(h.ts).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'}):h.time||'旧バージョンの履歴'),button('この記録を取り消す',()=>{if(confirm('この確認履歴を取り消しますか？')){history=history.filter(x=>x!==h);t.predictedStation='';persist();render();}},'secondary'));$('historyList').append(row);});}
$('accept').addEventListener('click',()=>{const t=active(),candidate=$('candidate').value,inf=SM.infer(t,history);if(t&&inf?.candidates.includes(candidate)){t.predictedStation=candidate;persist();render();toast(`${candidate}を採用しました`);}});$('unaccept').addEventListener('click',()=>{active().predictedStation='';persist();render();});
$('updateTimetable').onclick=()=>{edit();if(editing){$('registerTitle').textContent='時刻表を更新';$('ocrText').focus();}};$('add').onclick=newTrip;$('start').onclick=newTrip;$('edit').onclick=edit;$('editStops').onclick=edit;$('goCheck').onclick=()=>show('check');document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.page)));document.querySelectorAll('[data-result]').forEach(b=>b.addEventListener('click',()=>record(b.dataset.result)));
$('openService').onclick=()=>{const service=SM.services.find(s=>s.id===$('serviceSelect').value);if(service)window.open(service.url,'_blank','noopener,noreferrer');else toast('予約サービスを選択してください');};$('serviceSelect').onchange=()=>{if(active())renderCopies(active());};$('copySearch').onclick=()=>copy(`${$('searchFrom').value} → ${$('searchTo').value}`);
function login(){const id=ids[$('loginService').value]||'';$('loginId').value=id;$('rememberId').checked=!!id;}$('loginService').onchange=login;$('saveLogin').onclick=()=>{const service=$('loginService').value;if($('rememberId').checked&&$('loginId').value.trim())ids[service]=$('loginId').value.trim();else delete ids[service];try{localStorage.setItem('sm_loginIds',JSON.stringify(ids));toast('IDの設定を保存しました');}catch{toast('保存できませんでした');}login();if(active())renderCopies(active());};login();
$('enableNotification').onclick=async()=>{if(!('Notification'in window))return toast('この端末ではアプリ表示中の案内をご利用ください');try{const permission=await Notification.requestPermission();$('notificationStatus').textContent='通知の許可状態：'+permission;}catch{toast('通知を許可できませんでした');}};$('notificationStatus').textContent='アプリ表示中の接近案内は通知許可なしでも利用できます。';
$('clear').onclick=()=>{if(confirm('SeatMateの乗車・履歴・保存IDをすべて削除しますか？')){['sm_trips','sm_hist','sm_active','sm_loginIds','sm_notified'].forEach(k=>localStorage.removeItem(k));location.reload();}};
$('export').onclick=()=>{const data={version:13,trips,history,activeId:active()?.id,ids},url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=el('a');a.href=url;a.download='SeatMate-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('restore').onchange=async()=>{const file=$('restore').files[0];if(!file)return;try{if(file.size>5e6)throw Error();const d=JSON.parse(await file.text());if(!Array.isArray(d.trips)||d.trips.length>5||!Array.isArray(d.history)||d.trips.some(t=>!t||typeof t.id!=='string'||['date','train','from','to','car','seat'].some(k=>typeof t[k]!=='string')||!Array.isArray(t.stops)||t.stops.some(s=>!s||typeof s.name!=='string'||['arr','dep'].some(k=>s[k]!=null&&SM.mins(s[k])===null))))throw Error();if(!confirm('バックアップの内容で現在の乗車・履歴を置き換えますか？'))return;trips=d.trips;history=d.history.filter(h=>h&&typeof h==='object');activeId=d.activeId;ids=Object.fromEntries(Object.entries(d.ids||{}).filter(([k,v])=>SM.services.some(s=>s.id===k)&&typeof v==='string'));notified={};localStorage.setItem('sm_loginIds',JSON.stringify(ids));localStorage.removeItem('sm_notified');persist();login();show('home');toast('復元しました');}catch{toast('バックアップを読み込めませんでした');}$('restore').value='';};
render();setInterval(updateClock,15000);document.addEventListener('visibilitychange',()=>{if(!document.hidden){updateClock();}});window.addEventListener('pageshow',updateClock);
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').then(reg=>{reg.update().catch(()=>{});}).catch(()=>{});
