'use strict';
const $=id=>document.getElementById(id),el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f;}catch{return f;}};
let trips=read('sm_trips',[]),history=read('sm_hist',[]),ids=read('sm_loginIds',{}),notified=read('sm_notified',{}),calendarOpened=read('sm_calendarOpened',{}),activeId=localStorage.getItem('sm_active'),editing=null,draft=[],imageURL=null,selectedImage=null,ocrBusy=false,formVersion=0,toastTimer,staged=null,importMeta=null,segments=[];
if(!Array.isArray(trips))trips=[];if(!Array.isArray(history))history=[];
const uid=()=>crypto.randomUUID?crypto.randomUUID():'t'+Date.now()+Math.random().toString(36).slice(2);
const active=()=>trips.find(t=>t.id===activeId)||trips[0]||null;
const button=(label,fn,cls='secondary')=>{const b=el('button',label,cls);b.type='button';b.addEventListener('click',fn);return b;};
function toast(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,5500);}
function persist(){try{localStorage.setItem('sm_trips',JSON.stringify(trips));localStorage.setItem('sm_hist',JSON.stringify(history));if(active())localStorage.setItem('sm_active',active().id);else localStorage.removeItem('sm_active');return true;}catch{toast('端末への保存に失敗しました。空き容量を確認してください。');return false;}}
function show(page){if(['ride','check','history'].includes(page)&&!active()){toast('先に乗車を登録してください');page='home';}document.querySelectorAll('.screen').forEach(e=>e.classList.toggle('active',e.id===page));document.querySelectorAll('nav button').forEach(e=>e.classList.toggle('selected',e.dataset.page===page));render();scrollTo(0,0);}
async function copy(text){if(!text)return toast('コピーする情報がありません');try{await navigator.clipboard.writeText(text);toast('コピーしました');}catch{prompt('文字を選択してコピーしてください',text);}}
let batch=null;
let registrationStep=1;
function setStep(step){registrationStep=step;for(const id of ['importPanel','importReview','tripDetails','stopsPanel'])$(id).hidden=id==='importPanel'?step!==1:id==='importReview'?step!==2:step!==3;document.querySelectorAll('[data-step]').forEach(b=>{b.classList.toggle('current',Number(b.dataset.step)===step);b.disabled=Number(b.dataset.step)===2&&!staged||Number(b.dataset.step)===3&&!!staged;});$('viewSource').hidden=!imageURL;$('changeImport').hidden=step===1||!!batch;if(batch)document.querySelector('[data-step="1"]').disabled=true;}
function entryTab(mode){$('imageEntry').hidden=mode!=='image';$('textEntry').hidden=mode!=='text';$('imageTab').classList.toggle('selected',mode==='image');$('textTab').classList.toggle('selected',mode==='text');}
$('imageTab').onclick=()=>entryTab('image');$('textTab').onclick=()=>entryTab('text');$('manualEntry').onclick=()=>{staged=null;setStep(3);};$('changeImport').onclick=()=>setStep(1);
document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>setStep(Number(b.dataset.step)));
$('viewSource').onclick=()=>{$('sourceImage').src=imageURL;$('sourceImage').classList.remove('zoom');$('sourceZoom').textContent='拡大';$('sourceDialog').showModal();};$('sourceClose').onclick=()=>$('sourceDialog').close();$('sourceZoom').onclick=()=>{$('sourceImage').classList.toggle('zoom');$('sourceZoom').textContent=$('sourceImage').classList.contains('zoom')?'元の大きさ':'拡大';};
function seatRequirements(){const ordinary=/^JR.*線$/.test($('train').value);$('car').required=!ordinary;$('seat').required=!ordinary;$('seatHelp').textContent=ordinary?'在来線の区間は、号車・座席を空欄のまま保存できます。':'号車・座席は予約情報を確認して入力してください。番線や編成の両数とは異なります。';}
$('train').addEventListener('input',seatRequirements);
function resetForm(t){batch=null;$('importAdvanced').hidden=false;segments=[];$('batchBanner').hidden=true;$('batchStart').hidden=true;$('saveTrip').textContent='保存して乗車画面へ';formVersion++;staged=null;importMeta=t?.importMeta||null;$('importReview').hidden=true;$('registerTitle').textContent=t?'乗車を編集':'乗車を登録';editing=t?.id||null;for(const k of ['date','train','from','to','car','seat','neighbor','notifyBefore'])$(k).value=t?.[k]??(k==='date'?new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo'}).format(new Date()):k==='notifyBefore'?'10':'');draft=(t?.stops||[]).map(s=>({...s}));$('shot').value='';selectedImage=null;$('ocrText').value='';$('preview').hidden=true;$('ocrRun').disabled=true;$('formError').textContent='';$('ocrStatus').textContent='画像は端末内で処理し、保存しません。初回はOCRの読み込みに通信が必要です。';if(imageURL)URL.revokeObjectURL(imageURL);imageURL=null;renderEditor();show('register');entryTab('image');setStep(t?3:1);seatRequirements();}
function newTrip(){if(ocrBusy)return toast('OCRの完了をお待ちください');if(trips.length>=5)return toast('保存は最大5件です。不要な乗車を削除してください。');resetForm(null);}
function edit(){if(ocrBusy)return toast('OCRの完了をお待ちください');if(active())resetForm(active());}
function renderEditor(){$('stopSummary').textContent=`停車駅・時刻を編集（${draft.length}駅）`;$('stopDetails').open=draft.some(s=>!s.name||!s.arr&&!s.dep);const root=$('stopEditor');root.replaceChildren();draft.forEach((s,i)=>{const card=el('div',undefined,'stopedit'),row=el('div',undefined,'row');row.append(el('b',`${i+1}`),button('↑',()=>{if(i){[draft[i-1],draft[i]]=[draft[i],draft[i-1]];renderEditor();}}),button('↓',()=>{if(i<draft.length-1){[draft[i+1],draft[i]]=[draft[i],draft[i+1]];renderEditor();}}),button('削除',()=>{draft.splice(i,1);renderEditor();},'danger'));card.append(row);if(!s.name&&s.rawName)card.append(el('p',`OCRの文字：${s.rawName} / 画像で駅名を確認してください`,'note'));const field=(key,label,type)=>{const wrap=el('div'),l=el('label',label),input=el('input');input.id=`stop-${i}-${key}`;l.htmlFor=input.id;input.type=type;input.value=s[key]||'';input.addEventListener('input',()=>s[key]=input.value);wrap.append(l,input);return wrap;};card.append(field('name','駅名','text'));const g=el('div',undefined,'grid');g.append(field('arr','到着','time'),field('dep','出発','time'));card.append(g);root.append(card);});}
function formFields(){return Object.fromEntries(['date','train','from','to','car','seat'].map(k=>[k,$(k).value.trim()]));}
function parse(text){
 if(!String(text).trim())return toast('テキストを貼り付けるか、画像を読み取ってください');
 if(String(text).length>100000)return toast('取り込む列車1本分にテキストを絞ってください');
 staged=SM.parseTransit(text,Number($('date').value.slice(0,4))||undefined);
 segments=staged.segments||[];$('segmentPicker').hidden=!segments.length;$('importSegment').replaceChildren();segments.forEach((s,i)=>{const option=el('option',`${s.fields.train} / ${s.fields.from||'駅名未読'} → ${s.fields.to||'駅名未読'}`);option.value=i;$('importSegment').append(option);});
 if(segments.length){const index=editing?segments.findIndex(s=>s.fields.train===$('train').value):segments.findIndex(s=>SM.service(s.fields.train));$('importSegment').value=String(Math.max(0,index));staged=segments[Math.max(0,index)];}
 $('importMode').value=!editing&&draft.length?'merge':'replace';$('applyFields').checked=!editing;
 $('batchStart').hidden=!!editing||segments.length<2;setStep(2);renderReview();$('importReview').scrollIntoView({block:'start'});toast('抽出しました。候補と変更内容を確認してください');
}
function renderReview(){
 if(!staged)return;const existing=formFields(),fields=staged.fields;if(!editing)for(const key of ['train','date','from','to'])if(fields[key]===undefined)fields[key]='';const warnings=[...staged.warnings];const incompleteMerge=$('importMode').value==='merge'&&staged.stops.some(s=>!s.name);if(incompleteMerge)warnings.push('駅名が未読のまま追加・更新はできません。テキストの駅名を修正して再抽出するか、一覧を置き換えてから空欄を入力してください。');
 const same=(a,b)=>String(a||'').normalize('NFKC').replace(/\s/g,'');
 const mismatched=!!editing&&((fields.train&&existing.train&&!same(fields.train,existing.train))||(fields.date&&fields.date!==existing.date));
 if(editing&&(!fields.train||!fields.date))warnings.push('列車名または乗車日を読み取れていません。選択中の乗車に合う情報か確認してください。');
 if(mismatched)warnings.push('選択中の乗車と列車名または日付が異なります。この乗車には反映できません。正しい情報を取り込むか、新しい乗車を登録してください。');
 $('reviewTitle').textContent=editing?'時刻表の変更を確認':'列車と停車駅を確認';$('identityHint').textContent=editing?'更新時は日付・列車名・乗降駅を通常は保持します。号車・座席・隣席・確認履歴も引き継ぎます。':'切符画像に号車・座席があれば、新規登録に反映します。';
 $('importWarnings').replaceChildren();const critical=warnings.filter(w=>/未読|確認できません|読み取れ|異なり|逆戻り|OCR.*候補|反映できません/.test(w));critical.forEach(w=>$('importWarnings').append(el('p',w,'notice')));const other=warnings.filter(w=>!critical.includes(w));if(other.length){const d=el('details');d.append(el('summary',`読み取り上の注意（${other.length}件）`));other.forEach(w=>d.append(el('p',w,'note')));$('importWarnings').append(d);}
 $('importFields').replaceChildren();const labels={date:'乗車日',train:'列車名',from:'乗車駅候補',to:'降車駅候補',car:'号車',seat:'座席'};
 const buildReviewField=k=>{const wrap=el('div',undefined,['train','date'].includes(k)?'wide':''),label=el('label',labels[k]),input=el('input');input.id='review-'+k;label.htmlFor=input.id;input.type=k==='date'?'date':'text';input.value=fields[k]||'';input.addEventListener('change',()=>{fields[k]=input.value;});wrap.append(label,input);return wrap;};
 if(editing){const details=el('details',undefined,'review-complete');details.open=critical.length>0;details.append(el('summary','読み取った列車情報を確認'));const values=el('div',undefined,'review-value-list');Object.entries(fields).forEach(([k,v])=>{if(labels[k])values.append(el('p',`${labels[k]}：${v||'未読'}`));});details.append(values);$('importFields').append(details);}
 else {const keys=['train','date','from','to'],missing=keys.filter(k=>!fields[k]),complete=keys.filter(k=>fields[k]);if(missing.length){const issues=el('div',undefined,'review-issues');issues.append(el('p',`要確認：${missing.map(k=>labels[k]).join('・')}`));const grid=el('div',undefined,'review-grid');missing.forEach(k=>grid.append(buildReviewField(k)));issues.append(grid);$('importFields').append(issues);}if(complete.length){const details=el('details',undefined,'review-complete');details.append(el('summary',`読み取り済み情報（${complete.length}項目）`));const grid=el('div',undefined,'review-grid');complete.forEach(k=>grid.append(buildReviewField(k)));details.append(grid);$('importFields').append(details);}}
 const plan=SM.planStops(draft,staged.stops,$('importMode').value);const summary=el('p',`更新後 ${plan.stops.length}駅 / 変更 ${plan.changes.length}件`);$('importDiff').replaceChildren(summary);
 const time=s=>s?`${s.arr?'着 '+s.arr:'着 —'} / ${s.dep?'発 '+s.dep:'発 —'}`:'—';
 const table=el('table',undefined,'diff-table'),head=el('tr');['駅 / 変更','現在','取り込み後'].forEach(x=>head.append(el('th',x)));const thead=el('thead');thead.append(head);table.append(thead);const body=el('tbody');
 plan.stops.forEach(next=>{const old=draft.find(s=>s.name===next.name),change=plan.changes.find(c=>c.name===next.name),row=el('tr',undefined,change?'changed':'');row.append(el('th',(next.name||'駅名未読')+(change?' / '+change.type:'')),el('td',time(old)),el('td',time(next)));body.append(row);});
 plan.changes.filter(c=>c.type==='削除').forEach(c=>{const row=el('tr',undefined,'removed');row.append(el('th',c.name+' / 削除'),el('td',time(c.before)),el('td','—'));body.append(row);});table.append(body);$('importDiff').append(table);if(!editing)renderCandidateStops();
 $('applyImport').disabled=staged.blocked||mismatched||incompleteMerge||(!staged.stops.length&&!Object.keys(fields).length);
}
function renderCandidateStops(){const root=$('importDiff');const opened=new Set([...root.querySelectorAll('details[open]')].map(d=>d.dataset.index));root.replaceChildren();const heading=el('div',undefined,'review-caption');heading.append(el('b',`停車駅 ${staged.stops.length}駅`),el('span','タップして修正'));root.append(heading);staged.stops.forEach((s,i)=>{const missing=!s.name||!s.arr&&!s.dep;const detail=el('details',undefined,'review-stop'+(missing?' missing':''));detail.dataset.index=String(i);detail.open=missing||opened.has(String(i));const summary=el('summary');const text=()=>`${s.name||'駅名を入力'}　${s.arr?'着 '+s.arr+' ':''}${s.dep?'発 '+s.dep:''}`;summary.textContent=text();detail.append(summary);if(s.rawName)detail.append(el('p',`読み取り文字：${s.rawName}`,'note'));for(const key of ['name','arr','dep']){const label=el('label',key==='name'?'駅名':key==='arr'?'到着':'出発'),input=el('input');input.id=`candidate-stop-${i}-${key}`;label.htmlFor=input.id;input.type=key==='name'?'text':'time';input.value=s[key]||'';input.addEventListener('input',()=>{const old=s.name;s[key]=input.value||null;if(key==='name'){s.name=input.value;if(i===0&&(!staged.fields.from||staged.fields.from===old)){staged.fields.from=s.name;$('review-from').value=s.name;}if(i===staged.stops.length-1&&(!staged.fields.to||staged.fields.to===old)){staged.fields.to=s.name;$('review-to').value=s.name;}}summary.textContent=text();if($('importMode').value==='merge')$('applyImport').disabled=staged.stops.some(s=>!s.name);});detail.append(label,input);}root.append(detail);});}
$('importSegment').addEventListener('change',()=>{staged=segments[Number($('importSegment').value)];renderReview();});
$('importMode').addEventListener('change',renderReview);$('applyFields').addEventListener('change',renderReview);
$('applyImport').addEventListener('click',()=>{
 if(!staged||$('applyImport').disabled)return;
 const plan=SM.planStops(draft,staged.stops,$('importMode').value);
 const fields=$('applyFields').checked?staged.fields:{};
 const from=fields.from||$('from').value,to=fields.to||$('to').value;
 if(staged.stops.length&&$('importMode').value==='replace'&&draft.length&&((from&&!plan.stops.some(s=>s.name===from))||(to&&!plan.stops.some(s=>s.name===to))))return toast('乗車駅か降車駅が候補にありません。分割画像なら「追加・時刻更新」を選択してください');
 if($('applyFields').checked){for(const[k,v]of Object.entries(fields)){if(['date','train','from','to'].includes(k)||!editing&&['car','seat'].includes(k))$(k).value=v;}}
 if(staged.stops.length)draft=plan.stops;
 importMeta={source:'user-import',importedAt:new Date().toISOString(),mode:$('importMode').value};
 $('parseQuality').textContent=`取り込みを反映：${draft.length}駅。停車順・乗車日・着発時刻を確認して保存してください。`;
 staged=null;setStep(3);renderEditor();seatRequirements();$('tripDetails').scrollIntoView({block:'start'});toast('座席を入力して保存してください');
});
$('discardImport').addEventListener('click',()=>{if(batch){toast('まとめて登録を中止する場合は、上の中止ボタンを押してください');return;}staged=null;setStep(1);toast('候補を破棄しました');});
$('pasteText').addEventListener('click',async()=>{try{const text=await navigator.clipboard.readText();if(!text.trim())return toast('クリップボードにテキストがありません');$('ocrText').value=text;parse(text);}catch{toast('テキスト欄を長押しして「ペースト」してください');$('ocrText').focus();}});
$('ocrText').addEventListener('input',()=>{if(staged){staged=null;$('importReview').hidden=true;}});
let loader;
function loadOCR(){if(window.Tesseract)return Promise.resolve();if(loader)return loader;loader=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@6.0.1/dist/tesseract.min.js';const timeout=setTimeout(()=>{s.remove();loader=null;reject(new Error('timeout'));},45000);s.onload=()=>{clearTimeout(timeout);resolve();};s.onerror=()=>{clearTimeout(timeout);s.remove();loader=null;reject(new Error('load'));};document.head.append(s);});return loader;}
function chooseImage(f){selectedImage=f||null;staged=null;if(imageURL)URL.revokeObjectURL(imageURL);$('preview').hidden=true;$('ocrRun').disabled=!f;if(!f)return;if(!f.type.startsWith('image/')){$('ocrRun').disabled=true;return toast('画像ファイルを選択してください');}imageURL=URL.createObjectURL(f);$('preview').src=imageURL;$('preview').hidden=false;$('viewSource').hidden=false;}
$('shot').addEventListener('change',()=>chooseImage($('shot').files[0]));
$('ocrText').addEventListener('paste',e=>{const file=[...(e.clipboardData?.items||[])].find(item=>item.type.startsWith('image/'))?.getAsFile();if(file){e.preventDefault();chooseImage(file);toast('画像を貼り付けました。「画像をOCRで読み取る」を押してください');}});
$('ocrRun').addEventListener('click',async()=>{const file=selectedImage;if(!file||ocrBusy)return;ocrBusy=true;const version=formVersion;$('ocrRun').disabled=true;$('shot').disabled=true;$('parse').disabled=true;$('pasteText').disabled=true;let worker,ocrPhase='画像';
 try{$('ocrStatus').textContent='OCRを準備しています…';await loadOCR();worker=await Tesseract.createWorker(['jpn','eng'],1,{logger:m=>{if(m.status==='recognizing text')$('ocrStatus').textContent=`${ocrPhase} ${Math.round(m.progress*100)}%`;}});const text=await SM.readImage(worker,file,message=>{ocrPhase=message;$('ocrStatus').textContent=message+'…'},Number($('date').value.slice(0,4))||undefined);const result={data:{text}};if(version===formVersion){$('ocrText').value=result.data.text;parse(result.data.text);$('ocrStatus').textContent='読み取り完了。候補を確認・修正してください。';}}
 catch{$('ocrStatus').textContent='OCRを実行できませんでした。通信・画像形式を確認して再試行するか、テキスト貼り付け・手入力をご利用ください。';}
 finally{if(worker)await worker.terminate().catch(()=>{});ocrBusy=false;$('ocrRun').disabled=false;$('shot').disabled=false;$('parse').disabled=false;$('pasteText').disabled=false;}});
$('parse').addEventListener('click',()=>parse($('ocrText').value));$('addStop').addEventListener('click',()=>{draft.push({name:'',arr:null,dep:null});renderEditor();});
$('tripForm').addEventListener('submit',e=>{e.preventDefault();if(ocrBusy)return toast('OCRの完了後に保存してください');if(staged)return toast('取り込み候補を反映するか破棄してから保存してください');const o={id:editing||uid(),...Object.fromEntries(['date','train','from','to','car','seat','neighbor'].map(k=>[k,$(k).value.trim()])),importMeta,notifyBefore:Number($('notifyBefore').value),stops:draft.map(s=>({name:s.name.trim(),arr:s.arr||null,dep:s.dep||null}))};const error=s=>{$('formError').textContent=s;};
 if(!editing&&trips.length+(batch?batch.items.length:1)>5)return error('保存は5件までです。');if(o.from===o.to)return error('乗車駅と降車駅を別々に指定してください。');if(o.car&&!/^\d{1,2}$/.test(o.car))return error('号車は数字で指定してください。');o.seat=o.seat.normalize('NFKC').toUpperCase();o.neighbor=o.neighbor.normalize('NFKC').toUpperCase();if(o.neighbor&&o.neighbor===o.seat)return error('あなたの座席と隣席を別々に指定してください。');
 if(o.stops.some(s=>!s.name))return error('空欄の駅を入力するか削除してください。');if(new Set(o.stops.map(s=>s.name)).size!==o.stops.length)return error('停車駅の重複を修正してください。');if(o.stops.some(s=>s.arr&&SM.mins(s.arr)===null||s.dep&&SM.mins(s.dep)===null))return error('時刻をHH:MMで入力してください。');
 if(o.stops.length){const a=o.stops.findIndex(s=>s.name===o.from),b=o.stops.findIndex(s=>s.name===o.to);if(a<0||b<=a)return error('乗車駅・降車駅を停車駅に含め、運行順に並べてください。');const tl=SM.timeline(o);if(tl.length&&tl.at(-1).at-tl[0].at>24*60*60000)return error('停車時刻が24時間を超えています。順番と時刻を確認してください。');}
 if(batch){saveBatchLeg(o,error);return;}
 const old=trips.find(t=>t.id===editing);if(old){o.predictedStation=o.stops.some(s=>s.name===old.predictedStation)&&old.seat===o.seat&&old.neighbor===o.neighbor&&old.date===o.date&&old.car===o.car&&old.train===o.train?old.predictedStation:'';Object.assign(old,o);}else trips.push(o);activeId=o.id;if(persist()){try{sessionStorage.setItem('sm_recent_saved',o.id);}catch{}show('home');toast('乗車を保存しました。次は隣席を確認できます');}});
function option(select,value,text){const e=el('option',text);e.value=value;select.append(e);}
for(const s of SM.services){option($('serviceSelect'),s.id,s.name);option($('loginService'),s.id,s.name);}option($('serviceSelect'),'','選択してください');
let checkTrip=null;
function renderCheck(t,force=false){if(!t)return;const previousFrom=$('searchFrom').value,previousTo=$('searchTo').value,previousService=$('serviceSelect').value;const changed=checkTrip!==t.id||force;checkTrip=t.id;const service=SM.service(t.train);$('serviceSelect').value=changed?service?.id||'':previousService;$('serviceHint').textContent=service?`${service.name}を候補にしました。利用区間に応じて変更できます。`:'自動判定できません。予約サービスを選択してください。';
 const names=[...new Set([t.from,...(t.stops||[]).map(s=>s.name),t.to].filter(Boolean))];for(const id of ['searchFrom','searchTo']){$(id).replaceChildren();names.forEach(n=>option($(id),n,n));}const ts=SM.state(t);$('searchFrom').value=!changed&&names.includes(previousFrom)?previousFrom:ts.next?.name||t.from;$('searchTo').value=!changed&&names.includes(previousTo)?previousTo:t.to;renderCopies(t);}
function renderCopies(t){const entry=SM.services.find(s=>s.id===$('serviceSelect').value);$('serviceEntryHint').textContent=entry?.entryHint||'';$('openService').textContent=entry?.id==='smart-ex'?'ログインして列車検索へ ↗':'検索画面を開く ↗';$('copyRows').replaceChildren();const service=$('serviceSelect').value;const rows=[['日付',t.date],['列車',t.train],['検索する出発駅',$('searchFrom').value],['検索する到着駅',$('searchTo').value],['出発時刻',t.stops.find(s=>s.name===$('searchFrom').value)?.dep||''],['号車',t.car],['確認する隣席',t.neighbor]];if(ids[service])rows.push(['ログインID',ids[service]]);rows.forEach(([k,v])=>{const row=el('div',undefined,'copyrow'),info=el('div');info.append(el('small',k),el('b',v||'未設定'));row.append(info,button('コピー',()=>copy(v)));$('copyRows').append(row);});}
const weatherCache=new Map();let weatherToken=0;
function clock(ms){return ms?new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(ms)):'—';}
function calendarKey(t,cal){return cal?[t.id,t.predictedStation,cal.stationAt,cal.before].join('|'):'';}
function updateCalendar(t){
 const btn=$('calendarNotify'),title=$('calendarTitle'),status=$('calendarStatus'),cal=SM.googleCalendarUrl(t);
 if(!t.predictedStation){btn.disabled=true;btn.textContent='Googleカレンダー';title.textContent='接近通知';status.textContent='候補駅を採用すると設定できます';return;}
 if(!Number(t.notifyBefore)){btn.disabled=true;btn.textContent='通知なし';title.textContent=`${t.predictedStation} の通知`;status.textContent='乗車情報の編集から通知時刻を選べます';return;}
 if(!cal){btn.disabled=true;btn.textContent='時刻未登録';title.textContent=`${t.predictedStation} の通知`;status.textContent='候補駅の時刻を停車駅一覧に登録してください';return;}
 const key=calendarKey(t,cal),opened=!!calendarOpened[key];btn.disabled=false;btn.textContent=opened?'もう一度開く':'Googleカレンダー';title.textContent=`${t.predictedStation} ${cal.before}分前`;status.textContent=opened?`${clock(cal.start)} の予定をカレンダーで開きました`:`${clock(cal.start)} の予定として追加します`;
}
function openCalendar(){
 const t=active(),cal=t&&SM.googleCalendarUrl(t);if(!cal)return toast('候補駅と通知時刻を確認してください');
 const key=calendarKey(t,cal);calendarOpened[key]=new Date().toISOString();try{localStorage.setItem('sm_calendarOpened',JSON.stringify(calendarOpened));}catch{}
 window.open(cal.url,'_blank','noopener,noreferrer');updateCalendar(t);toast('Googleカレンダーを開きました。内容を確認して保存してください');
}
function weatherLabel(code){if(code===0)return ['☀','晴れ'];if([1,2].includes(code))return ['◐','晴れ時々くもり'];if(code===3)return ['●','くもり'];if([45,48].includes(code))return ['≋','霧'];if([51,53,55,56,57,61,63,65,66,67,80,81,82].includes(code))return ['╱','雨'];if([71,73,75,77,85,86].includes(code))return ['✦','雪'];if([95,96,99].includes(code))return ['ϟ','雷'];return ['○','天気'];}
async function updateWeather(t,state){
 const station=state.next?.name||t.to;if(!station){$('weatherCard').hidden=true;return;}const token=++weatherToken,now=Date.now(),cached=weatherCache.get(station);if(cached&&now-cached.time<30*60*1000){paintWeather(station,cached.data);return;}
 try{const geoUrl=`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(station)}&count=5&language=ja&countryCode=JP&format=json`;const geo=await fetch(geoUrl).then(r=>{if(!r.ok)throw Error();return r.json();});if(token!==weatherToken)return;let place=(geo.results||[]).find(x=>x.name===station)||(geo.results||[])[0];if(!place&&station!==t.to){const retry=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(t.to)}&count=3&language=ja&countryCode=JP&format=json`).then(r=>r.json());place=(retry.results||[])[0];}if(!place)throw Error();const wx=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${place.latitude}&longitude=${place.longitude}&current=temperature_2m,weather_code,precipitation&timezone=Asia%2FTokyo`).then(r=>{if(!r.ok)throw Error();return r.json();});if(token!==weatherToken)return;const data={temp:wx.current?.temperature_2m,code:wx.current?.weather_code,precip:wx.current?.precipitation,place:place.name};weatherCache.set(station,{time:Date.now(),data});paintWeather(station,data);}catch{if(token===weatherToken)$('weatherCard').hidden=true;}
}
function paintWeather(station,data){if(data?.temp==null){$('weatherCard').hidden=true;return;}const [icon,label]=weatherLabel(Number(data.code));$('weatherIcon').textContent=icon;$('weatherTemp').textContent=`${Math.round(data.temp)}°`;$('weatherStation').textContent=(data.place||station)+' ';$('weatherText').textContent=label;$('weatherCard').hidden=false;}
function renderMotion(t,now=Date.now()){
 const p=SM.journeyProgress(t,now),kind=SM.trainKind(t.train),pct=Math.round(p.ratio*100);$('progressFrom').textContent=t.from;$('progressTo').textContent=t.to;$('railDone').style.width=pct+'%';$('trainMarker').style.left=Math.min(88,pct*.88)+'%';$('trainSilhouette').dataset.kind=kind;$('trainTypeLabel').textContent=kind==='shinkansen'?'SHINKANSEN':kind==='limited'?'LIMITED EXPRESS':'TRAIN';$('progressCaption').textContent=`登録時刻表から算出した進行目安 ${pct}%`;
}
function renderNextAction(t){if(!t)return;const records=history.filter(h=>h.tripId===t.id||!h.tripId&&h.train===t.train),inf=SM.infer(t,history),card=$('nextActionCard'),title=$('nextActionTitle'),text=$('nextActionText'),btn=$('nextActionButton');let recent='';try{recent=sessionStorage.getItem('sm_recent_saved');}catch{}card.classList.toggle('fresh',recent===t.id);if(!t.neighbor){title.textContent='確認する隣席を設定';text.textContent='隣席を指定すると、座席確認と乗車駅推定を始められます。';btn.textContent='乗車情報を編集する →';btn.onclick=edit;return;}if(!records.length){title.textContent='最初の隣席チェック';text.textContent=`${t.neighbor} の空席状況を公式予約サイトで確認して、最初の記録を残しましょう。`;btn.textContent='隣席を確認する →';btn.onclick=()=>{try{sessionStorage.removeItem('sm_recent_saved');}catch{}show('check');};return;}if(inf&&!t.predictedStation){title.textContent='候補駅を確認';text.textContent=`確認結果から ${inf.candidates.join('・')} が候補になっています。通知に使う駅を採用してください。`;btn.textContent='候補駅を見る →';btn.onclick=()=>{$('adoption').scrollIntoView({behavior:'smooth',block:'center'});};return;}if(t.predictedStation){const cal=SM.googleCalendarUrl(t),opened=cal&&calendarOpened[calendarKey(t,cal)];if(cal&&!opened){title.textContent='カレンダー通知を追加';text.textContent=`${t.predictedStation} の ${cal.before}分前をGoogleカレンダーに追加できます。`;btn.textContent='Googleカレンダーを開く →';btn.onclick=openCalendar;return;}title.textContent='乗車中の状況を確認';text.textContent=`${t.predictedStation} を乗車候補駅として採用中です。停車駅と進行状況を確認できます。`;btn.textContent='停車駅を見る →';btn.onclick=()=>show('ride');return;}title.textContent='区間を変えてもう一度確認';text.textContent='検索の出発駅を次の停車駅へ進めて記録すると、乗車候補区間をさらに絞れます。';btn.textContent='座席確認を続ける →';btn.onclick=()=>show('check');}
function render(){const t=active();$('add').disabled=trips.length>=5;$('empty').hidden=!!trips.length;$('dashboard').hidden=!t;$('tripList').replaceChildren();trips.forEach(x=>{const row=el('div',undefined,`trip ${x.id===t?.id?'active':''}`),info=el('div');info.append(el('b',(x.journeyId?'乗継 '+(x.journeyOrder+1)+' / ':'')+x.train),el('small',`${x.date} / ${x.from} → ${x.to}`));row.append(info,button(x.id===t?.id?'選択中':'切替',()=>{activeId=x.id;persist();render();}),button('削除',()=>{if(confirm('この乗車と座席確認履歴を削除しますか？')){trips=trips.filter(y=>y.id!==x.id);history=history.filter(h=>h.tripId!==x.id);if(activeId===x.id)activeId=trips[0]?.id;persist();render();}},'danger'));$('tripList').append(row);});if(!t)return;
 renderNextAction(t);
 $('importStamp').textContent=t.importMeta?.importedAt?'情報の取り込み：'+new Date(t.importMeta.importedAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'}):'新しいスクショから時刻表を更新できます。';$('tripDate').textContent=t.date;$('trainTitle').textContent=t.train;$('route').textContent=`${t.from} → ${t.to}`;$('yourSeat').textContent=t.car&&t.seat?`${t.car}号車 ${t.seat}`:'未登録';$('targetSeat').textContent=t.neighbor||'未設定';renderMotion(t);updateClock();renderInference(t);$('rideTitle').textContent=t.train;$('stops').replaceChildren();const ts=SM.state(t);(t.stops||[]).forEach(s=>{const d=el('div',undefined,`stop ${ts.next?.name===s.name?'next':''}`);d.append(el('b',s.name),el('div',`${s.arr?'着 '+s.arr+'　':''}${s.dep?'発 '+s.dep:''}`));$('stops').append(d);});if(!t.stops?.length)$('stops').textContent='時刻表が未登録です。編集から追加できます。';renderCheck(t);renderHistory(t);}
function renderInference(t){const inf=SM.infer(t,history);$('inference').textContent=inf?`${inf.from}からの検索では空席、${inf.to}からは使用不可。候補：${inf.candidates.join('・')}。${inf.legacy?'旧履歴には検索区間がないため参考情報です。':''}`:'同じ隣席・到着駅で、出発駅を変えて確認した空席→使用不可の記録がたまると候補を表示します。';$('adoption').hidden=!inf;$('unaccept').hidden=!t.predictedStation;const selected=$('candidate').value;$('candidate').replaceChildren();if(inf){inf.candidates.forEach(n=>option($('candidate'),n,n));if(inf.candidates.includes(selected))$('candidate').value=selected;}}
function duration(m){return m>=1440?`${Math.floor(m/1440)}日${Math.floor(m%1440/60)}時間`:m+'分';}
function updateClock(){const t=active();if(!t)return;renderJourney(t);const state=SM.state(t),p=SM.prediction(t),tl=SM.timeline(t);$('current').textContent=state.current;$('next').textContent=state.next?.name||'—';const nextStop=state.next&&tl.find(s=>s.name===state.next.name);$('nextTime').textContent=nextStop?clock(nextStop.arrAt??nextStop.depAt):'—';$('remaining').textContent=state.minutes!==null?`あと ${duration(state.minutes)}`:'';renderMotion(t);const strip=$('predictionStrip');strip.classList.toggle('active',!!t.predictedStation);$('predictionHeadline').textContent=t.predictedStation?`${t.neighbor||'隣席'}は ${t.predictedStation} から使用の可能性`:'乗車駅はまだ推定されていません';$('prediction').textContent=t.predictedStation?p?(p.minutes<0?`${t.predictedStation}の登録時刻を過ぎました`:`${t.predictedStation}まであと約${duration(p.minutes)}`):`${t.predictedStation}の時刻を登録してください`:'座席確認の履歴から候補を絞り込みます';updateCalendar(t);updateWeather(t,state);if(p?.soon){const key=[t.id,t.date,t.predictedStation,p.at,t.notifyBefore].join('|');if(!notified[key]&&!document.hidden){notified[key]=true;try{localStorage.setItem('sm_notified',JSON.stringify(notified));}catch{}const message=`${t.predictedStation}まであと約${p.minutes}分。隣席 ${t.neighbor} の乗車候補駅です。`;toast(message);if('Notification'in window&&Notification.permission==='granted'&&navigator.serviceWorker)navigator.serviceWorker.ready.then(r=>r.showNotification('SeatMate 接近案内',{body:message,tag:key,icon:'icon-192.png'})).catch(()=>{});}}}
function record(status){const t=active();if(!t)return;if(!t.neighbor)return toast('乗車情報の編集で、確認する隣席を指定してください');const a=$('searchFrom').value,b=$('searchTo').value,names=(t.stops||[]).map(s=>s.name);if(a===b)return toast('検索した出発駅と到着駅を別々に選んでください');if(names.includes(a)&&names.includes(b)&&names.indexOf(a)>=names.indexOf(b))return toast('検索区間を運行順に選んでください');history.unshift({id:uid(),tripId:t.id,train:t.train,date:t.date,car:t.car,seat:t.neighbor,status,searchFrom:a,searchTo:b,station:a,ts:new Date().toISOString()});if(persist()){renderInference(t);renderHistory(t);toast(`${a} → ${b}：${status}を記録しました`);}}
function renderHistory(t){$('historyList').replaceChildren();const records=history.filter(h=>h.tripId===t.id||!h.tripId&&h.train===t.train);if(!records.length)$('historyList').textContent='まだ確認履歴がありません。';records.forEach(h=>{const row=el('div',undefined,'historyitem');row.append(el('b',`${h.searchFrom||h.station||'地点未登録'} → ${h.searchTo||'到着駅未登録'}`),el('div',`${h.car||'—'}号車 ${h.seat} / ${h.status}`),el('small',h.ts?new Date(h.ts).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'}):h.time||'旧バージョンの履歴'),button('この記録を取り消す',()=>{if(confirm('この確認履歴を取り消しますか？')){history=history.filter(x=>x!==h);t.predictedStation='';persist();render();}},'secondary'));$('historyList').append(row);});}
$('accept').addEventListener('click',()=>{const t=active(),candidate=$('candidate').value,inf=SM.infer(t,history);if(t&&inf?.candidates.includes(candidate)){t.predictedStation=candidate;persist();render();toast(`${candidate}を採用しました`);}});$('unaccept').addEventListener('click',()=>{active().predictedStation='';persist();render();});
$('calendarNotify').onclick=openCalendar;$('updateTimetable').onclick=()=>{edit();if(editing){$('registerTitle').textContent='時刻表を更新';setStep(1);entryTab('image');}};$('add').onclick=newTrip;$('start').onclick=newTrip;$('edit').onclick=edit;$('editStops').onclick=edit;$('goCheck').onclick=()=>show('check');document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.page)));document.querySelectorAll('[data-result]').forEach(b=>b.addEventListener('click',()=>record(b.dataset.result)));
$('openService').onclick=()=>{const service=SM.services.find(s=>s.id===$('serviceSelect').value);if(service)window.open(service.url,'_blank','noopener,noreferrer');else toast('予約サービスを選択してください');};$('serviceSelect').onchange=()=>{if(active())renderCopies(active());};$('copySearch').onclick=()=>copy(`${$('searchFrom').value} → ${$('searchTo').value}`);
function login(){const id=ids[$('loginService').value]||'';$('loginId').value=id;$('rememberId').checked=!!id;}$('loginService').onchange=login;$('saveLogin').onclick=()=>{const service=$('loginService').value;if($('rememberId').checked&&$('loginId').value.trim())ids[service]=$('loginId').value.trim();else delete ids[service];try{localStorage.setItem('sm_loginIds',JSON.stringify(ids));toast('IDの設定を保存しました');}catch{toast('保存できませんでした');}login();if(active())renderCopies(active());};login();
$('enableNotification').onclick=async()=>{if(!('Notification'in window))return toast('この端末ではアプリ表示中の案内をご利用ください');try{const permission=await Notification.requestPermission();$('notificationStatus').textContent='通知の許可状態：'+permission;}catch{toast('通知を許可できませんでした');}};$('notificationStatus').textContent='アプリ表示中の接近案内は通知許可なしでも利用できます。';
$('clear').onclick=()=>{if(confirm('SeatMateの乗車・履歴・保存IDをすべて削除しますか？')){['sm_trips','sm_hist','sm_active','sm_loginIds','sm_notified','sm_calendarOpened'].forEach(k=>localStorage.removeItem(k));location.reload();}};
$('export').onclick=()=>{const data={version:19,trips,history,activeId:active()?.id,ids},url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=el('a');a.href=url;a.download='SeatMate-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('restore').onchange=async()=>{const file=$('restore').files[0];if(!file)return;try{if(file.size>5e6)throw Error();const d=JSON.parse(await file.text());if(!Array.isArray(d.trips)||d.trips.length>5||!Array.isArray(d.history)||d.trips.some(t=>!t||typeof t.id!=='string'||['date','train','from','to','car','seat'].some(k=>typeof t[k]!=='string')||!Array.isArray(t.stops)||t.stops.some(s=>!s||typeof s.name!=='string'||['arr','dep'].some(k=>s[k]!=null&&SM.mins(s[k])===null))))throw Error();if(!confirm('バックアップの内容で現在の乗車・履歴を置き換えますか？'))return;trips=d.trips;history=d.history.filter(h=>h&&typeof h==='object');activeId=d.activeId;ids=Object.fromEntries(Object.entries(d.ids||{}).filter(([k,v])=>SM.services.some(s=>s.id===k)&&typeof v==='string'));notified={};localStorage.setItem('sm_loginIds',JSON.stringify(ids));localStorage.removeItem('sm_notified');persist();login();show('home');toast('復元しました');}catch{toast('バックアップを読み込めませんでした');}$('restore').value='';};
render();setInterval(updateClock,15000);document.addEventListener('visibilitychange',()=>{if(!document.hidden){updateClock();}});window.addEventListener('pageshow',updateClock);
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').then(reg=>{reg.update().catch(()=>{});}).catch(()=>{});

for(const id of ['searchFrom','searchTo'])$(id).addEventListener('change',()=>{if(active())renderCopies(active());});
$('copyAllSearch').onclick=()=>{const t=active();if(t)copy(`${t.date} ${t.train}\n${$('searchFrom').value} → ${$('searchTo').value}\n出発 ${t.stops.find(s=>s.name===$('searchFrom').value)?.dep||'未登録'}\n${t.car||'未登録'}号車 / 確認する隣席 ${t.neighbor||'未設定'}`);};
function loadBatchLeg(){
 const item=batch.items[batch.index],saved=batch.saved[batch.index];
 for(const k of ['date','train','from','to','car','seat','neighbor','notifyBefore'])$(k).value=saved?.[k]??(k==='notifyBefore'?'10':'');
 draft=[];staged=item;if(saved){item.fields={...item.fields,...Object.fromEntries(['date','train','from','to','car','seat'].map(k=>[k,saved[k]]))};item.stops=saved.stops.map(s=>({...s}));}
 $('batchBanner').hidden=false;$('batchProgress').textContent=`乗換経路 ${batch.index+1} / ${batch.items.length}本目：${item.fields.train}`;
 $('batchBack').disabled=batch.index===0;$('batchStart').hidden=true;$('segmentPicker').hidden=true;$('importMode').value='replace';$('applyFields').checked=true;$('importAdvanced').hidden=true;$('formError').textContent='';
 $('saveTrip').textContent=batch.index===batch.items.length-1?`${batch.items.length}本をまとめて保存`:'この列車を確認して次へ →';setStep(2);renderReview();scrollTo(0,0);
}
$('batchStart').onclick=()=>{if(segments.length<2)return;if(trips.length+segments.length>5)return toast(`あと${5-trips.length}件保存できます。この経路は${segments.length}本あるため、不要な乗車を削除するか1本ずつ登録してください。`);batch={id:uid(),index:0,items:structuredClone(segments),saved:[]};loadBatchLeg();};
$('batchBack').onclick=()=>{if(batch&&batch.index>0){if(registrationStep===3)batch.saved[batch.index]={...formFields(),neighbor:$('neighbor').value,notifyBefore:Number($('notifyBefore').value),stops:structuredClone(draft)};batch.index--;loadBatchLeg();}};
$('batchCancel').onclick=()=>{if(confirm('入力中の乗換経路を破棄しますか？保存済みの乗車は変更しません。')){resetForm(null);$('importAdvanced').hidden=false;}};
function saveBatchLeg(o,error){
 batch.saved[batch.index]=o;
 if(batch.index<batch.items.length-1){batch.index++;loadBatchLeg();return;}
 const problem=SM.validateJourney(batch.saved);if(problem)return error(problem+' 上の「前の列車を修正」から確認できます。');
 const added=batch.saved.map((t,i)=>({...t,journeyId:batch.id,journeyOrder:i}));const before=trips,prevId=activeId;trips=[...trips,...added];activeId=added[0].id;
 if(!persist()){trips=before;activeId=prevId;return;}
 batch=null;$('batchBanner').hidden=true;$('importAdvanced').hidden=false;show('home');toast(`${added.length}本の乗車をまとめて保存しました`);
}
function renderJourney(t){
 const legs=SM.journeyLegs(trips,t);$('journeyCard').hidden=legs.length<2;if(legs.length<2)return;
 $('journeyTitle').textContent=`旅の行程：${legs[0].from} → ${legs.at(-1).to}`;$('journeyLegs').replaceChildren();
 legs.forEach((leg,i)=>{const b=button(`${i+1}. ${leg.train}　${leg.from} → ${leg.to}`,()=>{activeId=leg.id;persist();render();});b.classList.toggle('selected',leg.id===t.id);$('journeyLegs').append(b);});
 const v=SM.transferState(legs,t);$('transferInfo').textContent=v.message;$('boardNext').hidden=!v.next;
 if(v.next){$('boardNext').textContent=`${v.next.train}に乗った →`;$('boardNext').onclick=()=>{activeId=v.next.id;persist();render();toast('次の列車に切り替えました');};}
}
