(function(root){
'use strict';
// Route screenshots use colored text and a vertical line that confuses text segmentation.
// Detect that layout from pixels; leave other images unchanged.
root.SM.prepareOCRImage=async function(file,bundle=false){
 const url=URL.createObjectURL(file);try{
 const img=new Image();img.src=url;await img.decode();
 const probe=document.createElement('canvas');const scale=Math.min(1,900/img.width);probe.width=Math.round(img.width*scale);probe.height=Math.round(img.height*scale);const ctx=probe.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,0,0,probe.width,probe.height);
 const w=probe.width,h=probe.height,data=ctx.getImageData(0,0,w,h).data;let left=0,right=w;
 const darkColumn=x=>{let n=0;for(let y=0;y<h;y+=8){const i=(y*w+x)*4;if(data[i]<25&&data[i+1]<25&&data[i+2]<25)n++;}return n/(Math.ceil(h/8))>.9;};
 while(left<w/3&&darkColumn(left))left++;while(right>w*2/3&&darkColumn(right-1))right--;
 let line=-1,best=0;for(let x=Math.round(left+(right-left)*.12);x<left+(right-left)*.32;x++){let count=0;for(let y=0;y<h;y+=2){const i=(y*w+x)*4,r=data[i],g=data[i+1],b=data[i+2];if(g>r+45&&g>b+30||b>r+65&&b>g+30)count++;}if(count>best){best=count;line=x;}}
 if(best<h*.10)return bundle?{image:file}:file;
 let sum=0,count=0;for(let x=Math.max(left,line-10);x<=Math.min(right-1,line+10);x++){let n=0;for(let y=0;y<h;y+=2){const i=(y*w+x)*4,r=data[i],g=data[i+1],b=data[i+2];if(g>r+45&&g>b+30||b>r+65&&b>g+30)n++;}if(n>=best*.8){sum+=x;count++;}}if(count)line=sum/count;
 // Keep the timetable and train headings, omit the fare sidebar.
 const width=Math.round((right-left)*.81),factor=Math.min(2,3500/h);const out=document.createElement('canvas');out.width=Math.round(width*factor);out.height=Math.round(h*factor);const c=out.getContext('2d',{willReadFrequently:true});c.drawImage(probe,left,0,width,h,0,0,out.width,out.height);const pixels=c.getImageData(0,0,out.width,out.height);
 for(let y=0;y<out.height;y++)for(let x=0;x<out.width;x++){const i=(y*out.width+x)*4,r=pixels.data[i],g=pixels.data[i+1],b=pixels.data[i+2];if(Math.abs(x/factor+left-line)<18){pixels.data[i]=pixels.data[i+1]=pixels.data[i+2]=255;}else if(b>r+40&&b>g+20||g>r+30&&g>b+20){pixels.data[i]=pixels.data[i+1]=pixels.data[i+2]=0;}}
 c.putImageData(pixels,0,0);const image=out.toDataURL('image/png');if(!bundle)return image;
 const x0=Math.round(line+(right-left)*.04),x1=Math.round(left+(right-left)*.73),groups=[];
 for(let y=0;y<h;y++){let n=0;for(let x=x0;x<x1;x++){const i=(y*w+x)*4;if(data[i+2]>data[i]+40&&data[i+2]>data[i+1]+20)n++;}if(n>5){if(!groups.length||y-groups.at(-1).at(-1)>6)groups.push([y]);else groups.at(-1).push(y);}}
 const rows=groups.filter(g=>{let min=x1,max=x0;for(const y of g)for(let x=x0;x<x1;x++){const i=(y*w+x)*4;if(data[i+2]>data[i]+40&&data[i+2]>data[i+1]+20){min=Math.min(min,x);max=Math.max(max,x);}}return max-min>=(right-left)*.06;}).map(g=>({top:g[0],bottom:g.at(-1),y:(g[0]+g.at(-1))/2}));
 if(rows.length<3||rows.length>50)return {image};
 function montage(kind){const canvas=document.createElement('canvas');canvas.width=kind==='names'?900:360;canvas.height=rows.length*180;const ct=canvas.getContext('2d',{willReadFrequently:true});ct.fillStyle='white';ct.fillRect(0,0,canvas.width,canvas.height);
 rows.forEach((row,i)=>{const top=kind==='names'?row.top-3:Math.round(row.y-40),bottom=kind==='names'?row.bottom+4:Math.round(row.y+40),start=kind==='names'?x0:Math.round(left+(right-left)*.02),end=kind==='names'?x1:Math.round(line-(right-left)*.035);const crop=document.createElement('canvas');crop.width=end-start;crop.height=bottom-top;const cc=crop.getContext('2d',{willReadFrequently:true});cc.drawImage(probe,start,top,crop.width,crop.height,0,0,crop.width,crop.height);const d=cc.getImageData(0,0,crop.width,crop.height);for(let j=0;j<d.data.length;j+=4){const r=d.data[j],g=d.data[j+1],b=d.data[j+2];const blue=b>r+30&&b>g+15;const ink=kind==='names'?blue:Math.min(r,g,b)<160;const v=ink?0:255;d.data[j]=d.data[j+1]=d.data[j+2]=v;}if(kind==='clocks'){const active=[];for(let yy=0;yy<crop.height;yy++){let min=crop.width,max=0;for(let xx=0;xx<crop.width;xx++){if(d.data[(yy*crop.width+xx)*4]===0){min=Math.min(min,xx);max=Math.max(max,xx);}}if(max-min>crop.width*.3)active.push(yy);}const runs=[];for(const yy of active){if(!runs.length||yy-runs.at(-1).at(-1)>3)runs.push([yy]);else runs.at(-1).push(yy);}const keep=runs.filter(g=>g.at(-1)-g[0]>=8);for(let yy=0;yy<crop.height;yy++)if(!keep.some(g=>yy>=g[0]-1&&yy<=g.at(-1)+1))for(let xx=0;xx<crop.width;xx++){const j=(yy*crop.width+xx)*4;d.data[j]=d.data[j+1]=d.data[j+2]=255;}}cc.putImageData(d,0,0);ct.drawImage(crop,20,i*180+15,crop.width*2,crop.height*2);});return canvas.toDataURL('image/png');}
 return {image,rows,factor,names:montage('names'),clocks:montage('clocks')};
 }finally{URL.revokeObjectURL(url);}
};
function lines(result){return (result.data.blocks||[]).flatMap(b=>(b.paragraphs||[]).flatMap(p=>p.lines||[]));}
root.SM.readImage=async function(worker,file,status=()=>{},year=new Date().getFullYear()){
 const parts=await root.SM.prepareOCRImage(file,true);status('画像全体の列車名・日付を読み取り中');const full=await worker.recognize(parts.image,{}, {blocks:true});if(!parts.rows)return full.data.text;
 const events=[];for(const l of lines(full)){const train=root.SM.parseOCR(l.text).fields.train;if(train&&/\d/.test(train))events.push({y:(l.bbox.y0+l.bbox.y1)/2/parts.factor,text:train.replace(/号$/,'')+'号'});}
 if(!events.length)return full.data.text;
 status('駅名だけを日本語で読み取り中');await worker.reinitialize('jpn');await worker.setParameters({tessedit_pageseg_mode:'6'});const names=await worker.recognize(parts.names,{}, {blocks:true});
 status('時刻だけを数字で読み取り中');await worker.reinitialize('eng');await worker.setParameters({tessedit_pageseg_mode:'6',tessedit_char_whitelist:'0123456789:'});const clocks=await worker.recognize(parts.clocks,{}, {blocks:true});
 const bucket=result=>{const out=parts.rows.map(()=>[]);for(const l of lines(result)){const i=Math.floor((l.bbox.y0+l.bbox.y1)/2/180);if(out[i])out[i].push(l.text);}return out;};const ns=bucket(names),ts=bucket(clocks),warnings=[];
 parts.rows.forEach((row,i)=>{const raw=ns[i].join(' ').normalize('NFKC').replace(/\s/g,'').replace(/\([^)]*\)/g,'').replace(/[A-Za-z!|]+$/g,'');let found=root.SM.resolveStation(raw);if(!found.name||found.corrected){const nearby=lines(full).filter(l=>Math.abs((l.bbox.y0+l.bbox.y1)/2/parts.factor-row.y)<20).map(l=>l.text).join(' ');const other=root.SM.resolveStation(nearby);if(other.name&&!other.corrected)found=other;}const name=found.name||`[未読${i}]`;if(found.corrected)warnings.push(`OCR補正候補：${raw} / ${name}（画像と照合してください）`);const times=[...ts[i].join(' ').matchAll(/(?<!\d)([01]?\d|2[0-3]):([0-5]\d)(?!\d)/g)].map(m=>m[1].padStart(2,'0')+':'+m[2]);const nearLine=lines(full).filter(l=>Math.abs((l.bbox.y0+l.bbox.y1)/2/parts.factor-row.y)<18&&!/更新/.test(l.text));const fullTimes=nearLine.flatMap(l=>[...l.text.matchAll(/(?<![\dA-Za-z])([01]\d|2[0-3]):([0-5]\d)(?!\d)/g)].map(m=>m[1]+':'+m[2]));if(times.length===1&&fullTimes.length===1&&times[0]!==fullTimes[0]){warnings.push(`OCR時刻候補：${name} ${fullTimes[0]}（別の読み取り ${times[0]}。画像と照合してください）`);times[0]=fullTimes[0];}const nearbyTimes=lines(full).filter(l=>Math.abs((l.bbox.y0+l.bbox.y1)/2/parts.factor-row.y)<40&&!/更新/.test(l.text)).flatMap(l=>[...l.text.matchAll(/(?<!\d)([01]?\d|2[0-3]):([0-5]\d)\s*着/g)].map(m=>m[1].padStart(2,'0')+':'+m[2]));if(times.length===1&&nearbyTimes.length&&!times.includes(nearbyTimes[0]))times.unshift(nearbyTimes[0]);events.push({y:row.y,text:times.length>=2?`${times[0]}着 ${name} ${times.at(-1)}発`:`${times[0]||''} ${name}`});});
 events.sort((a,b)=>a.y-b.y);const date=root.SM.parseOCR(full.data.text,year).fields.date;return [date||'',...warnings,'画像の経路を駅別に読み取り',...events.map(e=>e.text)].filter(Boolean).join('\n');
};
})(window);
