const test=require('node:test'),assert=require('node:assert/strict'),SM=require('../core.js');
test('ticket and timetable OCR normalization',()=>{const p=SM.parseOCR('２０２６年１０月９日\nしなの１２号\n８号車 １２番Ａ席\n松本 → 名古屋\n松本 １０：０３発\n塩尻 １０：１５着 １０：１６発\n名古屋 １２：０５着');assert.equal(p.fields.date,'2026-10-09');assert.equal(p.fields.seat,'12A');assert.equal(p.fields.car,'8');assert.equal(p.fields.from,'松本');assert.equal(p.fields.to,'名古屋');assert.equal(p.stops[1].arr,'10:15');assert.equal(p.stops[1].dep,'10:16');assert.equal(p.stops[2].arr,'12:05');});
test('unknown station and next-line times',()=>{const p=SM.parseOCR('新宿駅\n09:00発\n石和温泉駅\n10:30着');assert.equal(p.stops[1].name,'石和温泉');assert.equal(p.stops[1].arr,'10:30');});
test('reject invalid OCR dates and times',()=>{assert.equal(SM.parseOCR('2026年2月30日').fields.date,undefined);assert.equal(SM.mins('24:50'),null);assert.equal(SM.mins('00:00'),0);});
const t={id:'1',date:'2026-10-09',from:'東京',to:'名古屋',car:'1',neighbor:'12B',notifyBefore:10,predictedStation:'静岡',stops:[{name:'東京',dep:'23:45'},{name:'静岡',arr:'00:15',dep:'00:17'},{name:'名古屋',arr:'01:05'}]};
test('trip date and midnight timeline',()=>{assert.equal(SM.state(t,Date.parse('2026-10-09T23:55:00+09:00')).minutes,20);assert.equal(SM.state(t,Date.parse('2026-10-10T00:16:00+09:00')).current,'静岡に停車中');assert.equal(SM.state(t,Date.parse('2026-10-08T23:55:00+09:00')).current,'乗車前');assert.equal(SM.state(t,Date.parse('2026-10-10T01:06:00+09:00')).current,'降車駅に到着');});
test('notification threshold zero and trip date',()=>{assert.equal(SM.prediction(t,Date.parse('2026-10-10T00:10:00+09:00')).soon,true);assert.equal(SM.prediction({...t,notifyBefore:0},Date.parse('2026-10-10T00:10:00+09:00')).soon,false);assert.equal(SM.prediction(t,Date.parse('2026-10-09T00:10:00+09:00')).soon,false);});
const record=(status,from,ts,to='名古屋')=>({tripId:'1',car:'1',date:t.date,seat:'12B',status,searchFrom:from,searchTo:to,ts});
test('infer interval not false certainty',()=>{const hist=[record('空席','東京','1'),record('使用不可','名古屋','2')];assert.deepEqual(SM.infer(t,hist).candidates,['静岡','名古屋']);assert.equal(SM.infer(t,[record('空席','静岡','1'),record('使用不可','東京','2')]),null);assert.equal(SM.infer(t,[record('空席','東京','1'),record('使用不可','静岡','2','静岡')]),null);});
test('inference ignores other seat and newer unknown resets pair',()=>{assert.equal(SM.infer(t,[record('空席','東京','1'),{...record('使用不可','静岡','2'),seat:'13B'}]),null);assert.equal(SM.infer(t,[record('空席','東京','1'),record('不明','東京','2'),record('使用不可','静岡','3')]),null);});
test('reservation service mapping',()=>{assert.equal(SM.service('しなの12号').id,'e5489');assert.equal(SM.service('あずさ20号').id,'eki-net');assert.equal(SM.service('のぞみ1号').id,'smart-ex');assert.equal(SM.service('不明列車'),null);});

test('OCR spaces in Japanese station names',()=>{const p=SM.parseOCR('名 古屋 12:05 着');assert.equal(p.stops[0].name,'名古屋');});
test('past prediction time does not notify',()=>{assert.equal(SM.prediction(t,Date.parse('2026-10-10T00:15:30+09:00')).soon,false);});
