const test=require('node:test'),assert=require('node:assert/strict');require('../core.js');require('../train-heading.js');const {parseTransit:p,planStops:plan}=require('../transit.js');
test('Yahoo-style station then clocks on separate lines',()=>{const result=p('Yahoo!乗換案内\n2026年10月9日\n特急しなの12号\n停車駅一覧\n松本\n12:53発\n塩尻\n13:01着\n13:03発\n名古屋\n15:03着');assert.equal(result.fields.date,'2026-10-09');assert.deepEqual(result.stops,[{name:'松本',arr:null,dep:'12:53'},{name:'塩尻',arr:'13:01',dep:'13:03'},{name:'名古屋',arr:'15:03',dep:null}]);});
test('clock before station; no accidental previous clock reuse',()=>{const r=p('しなの12号\n12:53\n松本\n13:03\n塩尻\n15:03\n名古屋');assert.equal(r.stops[0].dep,'12:53');assert.equal(r.stops[1].dep,'13:03');assert.equal(r.stops[2].dep,'15:03');});
test('same-line time before station and unknown stations',()=>{const r=p('あずさ12号\n10:00 石和温泉駅\n10:10 山梨市駅\n10:20 四ツ谷駅');assert.deepEqual(r.stops.map(s=>s.name),['石和温泉','山梨市','四ツ谷']);assert.equal(r.stops[1].dep,'10:10');});
test('fullwidth OCR and spaced station names',()=>{const r=p('し な の １２号\n松 本１２：５３発\n塩 尻１３：０１着１３：０３発\n名 古 屋１５：０３着');assert.equal(r.fields.train,'しなの12号');assert.equal(r.stops[2].name,'名古屋');assert.equal(r.stops[1].dep,'13:03');});
test('date/time header does not change station-first orientation',()=>{const r=p('2026/10/9 10:00\n松本\n12:53発\n塩尻\n13:03発');assert.equal(r.stops[0].dep,'12:53');assert.equal(r.stops[1].dep,'13:03');});
test('multi train itinerary offers segments; shared URL gives clear fallback',()=>{assert.equal(p('しなの12号\n松本12:00\nあずさ20号\n新宿15:00').segments.length,2);assert.match(p('https://example.com/share/123').warnings.join(' '),/共有URL/);});
test('date without year uses selected year; missing dates never invented',()=>{assert.equal(p('10/9(金)\nしなの12号',2027).fields.date,'2027-10-09');assert.equal(p('松本12:00発\n名古屋15:00着').fields.date,undefined);});
const old=[{name:'松本',arr:null,dep:'12:53'},{name:'塩尻',arr:'13:01',dep:'13:03'},{name:'名古屋',arr:'15:03',dep:null}];
test('replace is immutable and exposes removed and changed stops',()=>{const next=[{name:'松本',arr:null,dep:'12:55'},{name:'名古屋',arr:'15:10',dep:null}];const r=plan(old,next);assert.equal(r.stops.length,2);assert.ok(r.changes.some(c=>c.type==='削除'&&c.name==='塩尻'));assert.equal(old[0].dep,'12:53');});
test('split screenshot merging inserts new station before matching anchor',()=>{const incoming=[{name:'塩尻',arr:null,dep:'13:04'},{name:'木曽福島',arr:null,dep:'13:35'},{name:'名古屋',arr:'15:10',dep:null}];const r=plan(old,incoming,'merge');assert.deepEqual(r.stops.map(s=>s.name),['松本','塩尻','木曽福島','名古屋']);assert.equal(r.stops[1].arr,'13:01');assert.equal(r.stops[1].dep,'13:04');});
test('malformed clocks and UI labels are not fake stations',()=>{const r=p('停車駅一覧\n出発\n25:80\n料金\n松本12:00発\n名古屋15:00着');assert.deepEqual(r.stops.map(s=>s.name),['松本','名古屋']);});

test('clock header with yearless date and duplicate train naming',()=>{const r=p('10/9(金) 10:00\nしなの12\nしなの12号\n松本\n12:53発\n名古屋\n15:03着',2026);assert.equal(r.blocked,false);assert.equal(r.fields.train,'しなの12号');assert.equal(r.stops[0].dep,'12:53');});
test('sparse merge uses clocks to place new station between existing stations',()=>{const r=plan([{name:'塩尻',arr:null,dep:'13:00'},{name:'木曽福島',arr:null,dep:'13:30'},{name:'名古屋',arr:'15:00',dep:null}],[{name:'塩尻',arr:null,dep:'13:01'},{name:'中津川',arr:null,dep:'14:00'}],'merge');assert.deepEqual(r.stops.map(s=>s.name),['塩尻','木曽福島','中津川','名古屋']);});
test('actual improved screenshot OCR keeps all stops and distinct transfer clocks',()=>{const r=p(require('fs').readFileSync(__dirname+'/fixtures/yahoo-enhanced.txt','utf8'),2026);assert.equal(r.segments.length,2);const [a,b]=r.segments;assert.equal(a.fields.train,'はくたか562号');assert.deepEqual(a.stops.map(s=>s.name),['福井','芦原温泉','加賀温泉','小松','金沢','新高岡','富山','黒部宇奈月温泉','糸魚川','上越妙高','長野']);assert.equal(a.stops[0].dep,'11:20');assert.deepEqual(a.stops.at(-1),{name:'長野',arr:'13:21',dep:null});assert.deepEqual(b.stops,[{name:'長野',arr:null,dep:'14:00'},{name:'篠ノ井',arr:null,dep:'14:09'},{name:'松本',arr:null,dep:'14:54'},{name:'塩尻',arr:'15:02',dep:null}]);});
test('provided noisy OCR never invents missing transfer station or borrows header clocks',()=>{const r=p(require('fs').readFileSync(__dirname+'/fixtures/yahoo-noisy.txt','utf8'),2026);const [a,b]=r.segments;assert.equal(a.fields.from,'福井');assert.equal(a.stops[0].dep,null);assert.equal(a.fields.to,'');assert.equal(a.stops.at(-1).name,'');assert.equal(a.stops.at(-1).arr,'13:21');assert.equal(a.stops.at(-1).dep,null);assert.equal(b.fields.from,'');assert.equal(b.stops[0].dep,'14:00');assert.match(a.warnings.join(' '),/逆戻り/);assert.match(b.warnings.join(' '),/駅名を確認できません|駅名を読み取れません/);assert.ok(!b.stops.some(s=>s.name==='長野'||s.name==='上越妙高'));});
test('adjacent station rows remain in first train and transfer is shared once',()=>{const r=p('10月4日\n福井11:20発\nはくたか562号\n金沢11:59\n上越妙高13:02\n長野13:21着14:00発\nしなの16号\n篠ノ井14:09\n塩尻15:02着',2026);assert.deepEqual(r.segments[0].stops.map(s=>s.name),['福井','金沢','上越妙高','長野']);assert.equal(r.segments[1].stops[0].dep,'14:00');});

test('summary time arrow is not a boarding station',()=>{const r=p('11:20→13:21 (2時間1分) 10月4日\n福井11:20発\nはくたか562号\n長野13:21着',2026);assert.equal(r.fields.from,'福井');assert.equal(r.fields.to,'長野');});
test('iPhone OCR retains missing stations and never accepts gibberish transfer name',()=>{const r=p(require('fs').readFileSync(__dirname+'/fixtures/yahoo-iphone.txt','utf8'),2026),[a,b]=r.segments;assert.equal(a.stops.length,11);assert.equal(b.stops.length,4);assert.equal(a.fields.to,'');assert.equal(b.fields.from,'');assert.equal(a.stops[1].name,'');assert.equal(a.stops[1].dep,'11:29');assert.equal(a.stops[2].dep,'11:37');assert.equal(a.stops.at(-1).arr,'13:21');assert.equal(b.stops[0].dep,'14:00');assert.equal(b.stops[1].name,'');assert.equal(b.stops[1].dep,'14:09');assert.ok(!r.segments.flatMap(s=>s.stops).some(s=>s.name==='史デブ'));});
test('single-character station corrections require a unique dictionary candidate',()=>{const match=require('../station-match');assert.deepEqual(match('稚ノ井'),{name:'篠ノ井',corrected:true});assert.equal(match('史デブ').name,'');assert.equal(match('ERAR').name,'');assert.equal(match('黒部宇奈月肖泉').name,'黒部宇奈月温泉');});
test('ordinary line and wrapped train number form distinct segments',()=>{const r=p(require('fs').readFileSync(__dirname+'/fixtures/nozomi-expanded.txt','utf8'),2026);assert.equal(r.segments.length,2);const [a,b]=r.segments;assert.equal(a.fields.train,'JR東海道本線');assert.deepEqual(a.stops.map(s=>s.name),['東京','新橋','品川']);assert.equal(a.stops.at(-1).arr,'05:48');assert.equal(b.fields.train,'のぞみ99号');assert.equal(b.stops[0].dep,'06:00');assert.equal(b.stops.length,11);assert.equal(b.stops.at(-1).arr,'10:46');assert.equal(b.fields.date,'2026-11-07');});
test('train headings do not concatenate a completed number or ordinary platform numbers',()=>{assert.equal(SM.trainHeading('のぞみ9号','9号車'),'のぞみ9号');assert.equal(SM.trainHeading('JR東海道本線','発9番線'),'JR東海道本線');assert.equal(SM.trainHeading('のぞみ9','9号(N700系)'),'のぞみ99号');assert.equal(SM.trainHeading('のぞみ','99号'),'のぞみ99号');});
test('extra character after minutes is an explicit repair, invalid hour is never fixed',()=>{require('../station-match');assert.deepEqual(SM.clocksFromOCR('05:48\n06:005'),{times:['05:48','06:00'],repairs:[{raw:'06:005',time:'06:00'}]});assert.deepEqual(SM.clocksFromOCR('26:005'),{times:[],repairs:[]});});
test('transfer arrival is never reused as next departure',()=>{const r=p('11月7日\n05:40 東京\nJR東海道本線\n05:48着 品川\nのぞみ99号\n10:46着 博多',2026);assert.equal(r.segments[0].stops.at(-1).arr,'05:48');assert.equal(r.segments[1].stops[0].dep,null);});
